### ISSUE TITLE
Thiết kế và viết code xử lý form Đăng nhập

### ISSUE THREAD

**Issue by vanluong0458** [TranTuan1306/Project_CNPM#10]

**Comment by chun14799** [comment]
https://github.com/TranTuan1306/Project_CNPM/tree/main/login_firebase_1

**Comment by chun14799** [comment]
[Login form.txt](https://github.com/TranTuan1306/Project_CNPM/files/6448044/Login.form.txt)
[Login screen.txt](https://github.com/TranTuan1306/Project_CNPM/files/6448045/Login.screen.txt)
