### ISSUE TITLE
Phân tích yêu cầu chức năng, phi chức năng.

### ISSUE THREAD

**Issue by chun14799** [TranTuan1306/Project_CNPM#2]

**Comment by chun14799** [comment]
[Yêu cầu chức năng.txt](https://github.com/TranTuan1306/Project_CNPM/files/6133956/Yeu.c.u.ch.c.nang.txt)

**Comment by TranTuan1306** [comment]
**Yêu cầu phi chức năng:** 
- Bố cục rõ ràng giao diện đẹp mắt thân thiện với người dùng.
- Xây dựng ứng dụng trên nền tảng website.
