### ISSUE TITLE
1. Sử dụng ngôn ngữ có cấu trúc

### ISSUE THREAD

**Issue by TranTuan1306** [TranTuan1306/Project_CNPM#3]
a.	Mô tả.
b.	Dòng sự kiện chính.
c.	Các dòng sự kiện khác.
d.	Điều kiện tiên quyết.
e.	Trạng thái hệ thống sau khi thực hiện use case
f.	Các điểm mở rộng.

**Comment by TranTuan1306** [comment]
[Đặc tả - Trần Văn Tuấn.docx](https://github.com/TranTuan1306/Project_CNPM/files/6209035/D.c.t.-.Tr.n.Van.Tu.n.pdf)

**Comment by TranTuan1306** [comment]
[Uploading Đặc tả - Trần Văn Tuấn.docx…]()

**Comment by TranTuan1306** [comment]
[Đặc tả - Trần Văn Tuấn.docx](https://github.com/TranTuan1306/Project_CNPM/files/6209044/D.c.t.-.Tr.n.Van.Tu.n.docx)

**Comment by chun14799** [comment]
[Đặc-tả-usecase.docx - Hoàng Long](https://github.com/TranTuan1306/Project_CNPM/files/6209068/D.c-t.-usecase.docx)

**Comment by nguyencongchien1303** [comment]
[Đặc tả usecase.docx](https://github.com/TranTuan1306/Project_CNPM/files/6214990/D.c.t.usecase.docx)

**Comment by vanluong0458** [comment]
Dạ em chào các anh, ở task này em có một số ý kiến mong các anh xem xét:
- File đặc tả của anh Tuấn có chức năng Đăng xuất, em nghĩ nên lọc bỏ và sửa lại thành Đăng ký
- Ngoài các chức năng của user, còn cần đặc tả chức năng Quản lý bài tập, Quản lý user của Admin
- Đặc tả chức năng report theo kcal/tháng
