### ISSUE TITLE
2. Sử dụng bảng

### ISSUE THREAD

**Issue by TranTuan1306** [TranTuan1306/Project_CNPM#4]
mô tả action trong cách 1

**Comment by TranTuan1306** [comment]
[Sử dụng bảng - Trần Văn Tuấn.docx](https://github.com/TranTuan1306/Project_CNPM/files/6210498/S.d.ng.b.ng.-.Tr.n.Van.Tu.n.docx)

**Comment by chun14799** [comment]
[Đặc tả dạng bảng.docx - Hoàng Long](https://github.com/TranTuan1306/Project_CNPM/files/6210990/D.c.t.d.ng.b.ng.docx)

**Comment by nguyencongchien1303** [comment]
[Đặc tả dạng bảng.docx](https://github.com/TranTuan1306/Project_CNPM/files/6214991/D.c.t.d.ng.b.ng.docx)

**Comment by nguyencongchien1303** [comment]
[Đặc tả dạng bảng.docx - Chiến](https://github.com/TranTuan1306/Project_CNPM/files/6214993/D.c.t.d.ng.b.ng.docx)

**Comment by vanluong0458** [comment]
Dạ task này phụ thuộc task trước nên yêu cầu cũng tương tự:
- Thay đổi đặc tả bảng cho chức năng Đăng xuất thành Đăng ký
- Viết đặc tả dạng bảng cho chức năng Quản lý bài tập, Quản lý user, report
