### ISSUE TITLE
3. Sử dụng sơ đồ usercase

### ISSUE THREAD

**Issue by TranTuan1306** [TranTuan1306/Project_CNPM#5]

**Comment by TranTuan1306** [comment]
![image](https://user-images.githubusercontent.com/45895121/112607183-83365700-8e4b-11eb-9ecc-292851efd9ab.png)

**Comment by vanluong0458** [comment]
Em nghĩ cần bổ sung chức năng Quản lý user và tên các usecase là các động từ
![image](https://user-images.githubusercontent.com/72118812/113923829-37a08780-9813-11eb-8ef2-92c8ec8b04ee.png)
