### ISSUE TITLE
1. Lược đồ use case

### ISSUE THREAD

**Issue by TranTuan1306** [TranTuan1306/Project_CNPM#6]
actor, function và bảng mô tả chức năng của function

**Comment by TranTuan1306** [comment]
[Lược đồ use case.docx](https://github.com/TranTuan1306/Project_CNPM/files/6253939/L.c.d.use.case.docx)

**Comment by chun14799** [comment]
[Lược đồ Usecase-Long.docx](https://github.com/TranTuan1306/Project_CNPM/files/6262017/L.c.d.Usecase-Long.docx)

**Comment by nguyencongchien1303** [comment]
[Usecase_Chiến.docx](https://github.com/TranTuan1306/Project_CNPM/files/6262027/Usecase_Chi.n.docx)

**Comment by vanluong0458** [comment]
Dạ task này cũng cần bổ sung lược đồ cho 2 chức năng của Admin: quản lý bài tập và user

**Comment by chun14799** [comment]
okay em, anh sẽ bổ sung

**Comment by vanluong0458** [comment]
Dạ em cảm ơn anh nhiều. anh có thể cho em xin face hay zalo gì để
liên lạc cho dễ được không ạ

Vào 20:19 Th 4, 14 thg 4 2021 Hoàng Long ***@***.***> đã viết:

**Comment by chun14799** [comment]
Fb.com/chun.reus nha em

Vào 20:30, Th 4, 14 thg 4, 2021 vanluong0458 ***@***.***> đã
viết:
