### ISSUE TITLE
2. Sequence Diagram

### ISSUE THREAD

**Issue by TranTuan1306** [TranTuan1306/Project_CNPM#7]

**Comment by TranTuan1306** [comment]
[sequence.docx](https://github.com/TranTuan1306/Project_CNPM/files/6254012/sequence.docx)

**Comment by chun14799** [comment]
[Sequences-Long.docx](https://github.com/TranTuan1306/Project_CNPM/files/6262223/Sequences-Long.docx)

**Comment by nguyencongchien1303** [comment]
[Sequences.docx](https://github.com/TranTuan1306/Project_CNPM/files/6262247/Sequences.docx)
