### ISSUE TITLE
3. Class Diagram

### ISSUE THREAD

**Issue by TranTuan1306** [TranTuan1306/Project_CNPM#8]

**Comment by TranTuan1306** [comment]
[class diagram.docx](https://github.com/TranTuan1306/Project_CNPM/files/6254283/class.diagram.docx)

**Comment by chun14799** [comment]
[ClassDiagram-Long.docx](https://github.com/TranTuan1306/Project_CNPM/files/6262356/ClassDiagram-Long.docx)

**Comment by nguyencongchien1303** [comment]
[class_diagram.docx](https://github.com/TranTuan1306/Project_CNPM/files/6262357/class_diagram.docx)
